
["Feature Options"]

	["Feature Options".Dungeons]
		#
		# Add End themed dungeon to End biomes outside the Enderdragon island.
		# How often dungeons will attempt to spawn per chunk.
		#  0 for no Dungeons at all and 1000 for max Dungeon spawnrate.
		#Range: 0 ~ 1000
		endDungeonSpawnrate = 8
		#
		# Replace vanilla dungeon in Swamp biomes with Swamp themed dungeon.
		# How often dungeons will attempt to spawn per chunk.
		#  0 for no Dungeons at all and 1000 for max Dungeon spawnrate.
		# Note: Vanilla Dungeons will spawn again when this is set to 0.
		#Range: 0 ~ 1000
		swampDungeonSpawnrate = 8
		#
		# Replace vanilla dungeon in Jungle biomes with Jungle themed dungeon.
		# How often dungeons will attempt to spawn per chunk.
		#  0 for no Dungeons at all and 1000 for max Dungeon spawnrate.
		# Note: Vanilla Dungeons will spawn again when this is set to 0.
		#Range: 0 ~ 1000
		jungleDungeonSpawnrate = 8
		#
		# Add the custom dungeons to modded biomes of the same categories/type.
		addDungeonsToModdedBiomes = true
		#
		# Add Nether themed dungeon to Nether biomes.
		# How often dungeons will attempt to spawn per chunk.
		#  0 for no Dungeons at all and 1000 for max Dungeon spawnrate.
		#Range: 0 ~ 1000
		netherDungeonSpawnrate = 8
		#
		# Replace vanilla dungeon in Mushroom biomes with Mushroom themed dungeon.
		# How often dungeons will attempt to spawn per chunk.
		#  0 for no Dungeons at all and 1000 for max Dungeon spawnrate.
		# Note: Vanilla Dungeons will spawn again when this is set to 0.
		#Range: 0 ~ 1000
		mushroomDungeonSpawnrate = 8
		#
		# Replace vanilla dungeon in Desert biomes with Desert themed dungeon.
		# How often dungeons will attempt to spawn per chunk.
		#  0 for no Dungeons at all and 1000 for max Dungeon spawnrate.
		# Note: Vanilla Dungeons will spawn again when this is set to 0.
		#Range: 0 ~ 1000
		desertDungeonSpawnrate = 8
		#
		# Replace vanilla dungeon in icy/snow biomes with icy/snow themed dungeon.
		# How often dungeons will attempt to spawn per chunk.
		#  0 for no Dungeons at all and 1000 for max Dungeon spawnrate.
		# Note: Vanilla Dungeons will spawn again when this is set to 0.
		#Range: 0 ~ 1000
		snowDungeonSpawnrate = 8
		#
		# Replace vanilla dungeon in Badlands biomes with Badlands themed dungeon.
		# How often dungeons will attempt to spawn per chunk.
		#  0 for no Dungeons at all and 1000 for max Dungeon spawnrate.
		# Note: Vanilla Dungeons will spawn again when this is set to 0.
		#Range: 0 ~ 1000
		badlandsDungeonSpawnrate = 8
		#
		# Add ocean themed dungeon to ocean biomes. These will spawn on
		# the ocean's floor and inside water filled caves and ravines.
		#
		# How often dungeons will attempt to spawn per chunk.
		#  0 for no dungeons at all and 1000 for max dungeon spawnrate.
		#
		# Note: Vanilla Dungeons will still generate if the biome has 
		# them which is unlike the other modded dungeons from this mod
		# as those would normally replace the Vanilla Dungeons.
		#Range: 0 ~ 1000
		oceanDungeonSpawnrate = 8
		#
		# Replace vanilla dungeon in Dark Forest biomes with Dark Forest themed dungeon.
		# How often dungeons will attempt to spawn per chunk.
		#  0 for no Dungeons at all and 1000 for max Dungeon spawnrate.
		# Note: Vanilla Dungeons will spawn again when this is set to 0.
		#Range: 0 ~ 1000
		darkForestDungeonSpawnrate = 8

	["Feature Options"."Small Wells"]
		#
		# Add the custom wells to modded biomes of the same categories/type.
		addWellsToModdedBiomes = true
		#
		# Adds mossy stone themed wells to Jungles, Dark Oak, and Swamp biomes.
		# This effects how often wells will attempt to spawn per chunk.
		# The chance of a well generating at a chunk is 1/spawnrate.
		# 1 for wells spawning in every chunk and 10000 for no wells.
		#Range: 1 ~ 10000
		mossyStoneWellSpawnrate = 350
		#
		# Adds a wood themed wells to Forest and Birch Forest biomes.
		# This effects how often wells will attempt to spawn per chunk.
		# The chance of a well generating at a chunk is 1/spawnrate.
		# 1 for wells spawning in every chunk and 10000 for no wells.
		#Range: 1 ~ 10000
		forestWellSpawnrate = 350
		#
		# Adds Nether themed wells to Nether biomes.
		# This effects how often wells will attempt to spawn per chunk.
		# The chance of a well generating at a chunk is 1/spawnrate.
		# 1 for wells spawning in every chunk and 10000 for no wells.
		#Range: 1 ~ 10000
		netherWellSpawnrate = 350
		#
		# Adds Snow themed wells to snowy and icy biomes.
		# This effects how often wells will attempt to spawn per chunk.
		# The chance of a well generating at a chunk is 1/spawnrate.
		# 1 for wells spawning in every chunk and 10000 for no wells.
		#Range: 1 ~ 10000
		snowWellSpawnrate = 350
		#
		# Determines if Wells can have a chance of spawning a Bell.
		canHaveBells = true
		#
		# Adds Badlands themed wells to Badlands biomes.
		# This effects how often wells will attempt to spawn per chunk.
		# The chance of a well generating at a chunk is 1/spawnrate.
		# 1 for wells spawning in every chunk and 10000 for no wells.
		#Range: 1 ~ 10000
		badlandsWellSpawnrate = 350

	["Feature Options".Misc]
		#
		# Adds a large tree somewhat uncommonly to Swamp biome and replaces
		# all vanilla trees in Swamp Hills biome with the larger tree.
		hornedSwampTree = true
		#
		# Adds tiny boulders to Taiga Mountains and Snowy Taiga Mountains biomes 
		# that can contain small amounts of Coal and Iron ores.
		boulderTiny = true
		#
		# Add the custom features to modded biomes of the same categories/type.
		addMiscToModdedBiomes = true
		#
		# Replaces boulders in Giant Tree Taiga Hills and Giant Spruce Taiga Hills
		# biomes with a larger boulder that can contain Coal, Iron, and extremely
		# rarely, can also have Diamond Ores.
		boulderGiant = true

["Structure Options"]

	["Structure Options".Igloos]
		#
		# Add Grassy Igloos to modded biomes that are
		# most likely grassy fields or temperate forests.
		addGrassyIglooToModdedBiomes = true
		#
		# How rare are Stone Igloos in Giant Tree Taiga biomes.
		# 1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		stoneIglooSpawnrate = 30
		#
		# How rare are Grassy Igloos in Plains and Forests.
		# 1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		grassyIglooSpawnrate = 30
		#
		# Add Stone Igloos to modded biomes that are
		# most likely Giant Tree Taiga variants.
		addStoneIglooToModdedBiomes = true

	["Structure Options"."Jungle Fortress"]
		#
		# How rare are Jungle Fortresses.
		# 1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		jungleFortressSpawnrate = 48
		#
		# Controls whether loot chests spawn or not in Jungle Fortresses.
		lootChestsJF = true
		#
		# How often Silverfish Blocks will generate in Jungle Fortress as a percentage.
		# Note: Mossy Stone Bricks block cannot be infected by Silverfish
		# 0 for no Silverfish Blocks and 100 for max spawnrate.
		#Range: 0.0 ~ 100.0
		silverfishSpawnrateJF = 0.5
		#
		# Silverfish Mob Spawners generate in Stone Fortresses.
		# If turned off, the spawners will become Skeleton spawners.
		allowSilverfishSpawnerJF = true
		#
		# Add Jungle Fortress to modded jungle biomes.
		addJungleFortressToModdedBiomes = true

	["Structure Options".Mineshaft]
		#
		# Replace Mineshafts in Jungle biomes with a Jungle themed Mineshaft.
		# How often Mineshafts will spawn.
		# 0 for no Mineshafts and 1000 for max spawnrate.
		# Note: Vanilla Mineshafts will spawn again when this is set to 0 and game is restarted.
		#Range: 0 ~ 1000
		jungleMineshaftSpawnrate = 40
		#
		# Replace Mineshafts in Taiga biomes with a Taiga themed Mineshaft.
		# How often Mineshafts will spawn.
		# 0 for no Mineshafts and 1000 for max spawnrate. Note: Vanilla Mineshafts will spawn again when this is set to 0 and game is restarted.
		#Range: 0 ~ 1000
		taigaMineshaftSpawnrate = 40
		#
		# Replace Mineshafts in Birch biomes with a Birch themed Mineshaft.
		# How often Mineshafts will spawn.
		# 0 for no Mineshafts and 1000 for max spawnrate.
		# Note: Vanilla Mineshafts will spawn again when this is set to 0 and game is restarted.
		#Range: 0 ~ 1000
		birchMineshaftSpawnrate = 40
		#
		# Replace Mineshafts in Desert biomes with a Desert themed Mineshaft.
		# How often Mineshafts will spawn.
		# 0 for no Mineshafts and 1000 for max spawnrate.
		# Note: Vanilla Mineshafts will spawn again when this is set to 0 and game is restarted.
		#Range: 0 ~ 1000
		desertMineshaftSpawnrate = 40
		#
		# Replace Mineshafts in Ocean biomes with an Ocean themed Mineshaft.
		# How often Mineshafts will spawn.
		# 0 for no Mineshafts and 1000 for max spawnrate.
		# Note: Vanilla Mineshafts will spawn again when this is set to 0 and game is restarted.
		#Range: 0 ~ 1000
		oceanMineshaftSpawnrate = 40
		#
		# Replace Mineshafts in Mountain (Extreme Hills) biomes with a Stone themed Mineshaft.
		# How often Mineshafts will spawn.
		# 0 for no Mineshafts and 1000 for max spawnrate.
		# Note: Vanilla Mineshafts will spawn again when this is set to 0 and game is restarted.
		#Range: 0 ~ 1000
		stoneMineshaftSpawnrate = 40
		#
		# Controls whether loot chests spawn or not in modded Mineshafts.
		lootChestsMS = true
		#
		# Add Nether themed Mineshafts to Nether biomes.
		# How often Mineshafts will spawn.
		# 0 for no Mineshafts and 1000 for max spawnrate.
		#Range: 0 ~ 1000
		netherMineshaftSpawnrate = 40
		#
		# Add End themed Mineshafts to End biomes outside the Enderdragon island.
		# How often Mineshafts will spawn.
		# 0 for no Mineshafts and 1000 for max spawnrate.
		#Range: 0 ~ 1000
		endMineshaftSpawnrate = 40
		#
		# Add the custom Mineshafts to modded biomes of the same categories/type.
		addMineshaftsToModdedBiomes = true
		#
		# Replace Mineshafts in Swamps and Dark Forests with a
		# swampy/dark oak themed Mineshaft.
		# Note: Vanilla Mineshafts will spawn again when this is set to 0 and game is restarted.
		#Range: 0 ~ 1000
		swampAndDarkForestMineshaftSpawnrate = 40
		#
		# Replace Mineshafts in Snowy/Icy biomes with an Ice themed Mineshaft.
		# Note: Snowy Taiga Biomes will get Ice Mineshaft instead of Taiga theme.
		# How often Mineshafts will spawn.
		# 0 for no Mineshafts and 1000 for max spawnrate.
		# Note: Vanilla Mineshafts will spawn again when this is set to 0 and game is restarted.
		#Range: 0 ~ 1000
		icyMineshaftSpawnrate = 40
		#
		# Replace Mineshafts in Savanna biomes with a Savanna themed Mineshaft.
		# How often Mineshafts will spawn.
		# 0 for no Mineshafts and 1000 for max spawnrate.
		# Note: Vanilla Mineshafts will spawn again when this is set to 0 and game is restarted.
		#Range: 0 ~ 1000
		savannaMineshaftSpawnrate = 40

	["Structure Options"."Nether Temple"]
		#
		# Controls whether loot chests spawn or not in Nether Temples.
		lootChestsNT = true
		#
		# How rare are Nether Temples in Nether.
		# 1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		netherTempleSpawnrate = 30
		#
		# Add Jungle Fortress to modded jungle biomes.
		addNetherTempleToModdedBiomes = true

	["Structure Options".Stronghold]
		#
		# How often Silverfish Blocks will generate in Strongholds as a percentage.
		# Note: Mossy Stone Bricks block cannot be infected by Silverfish
		# 0 for no Silverfish Blocks and 100 for max spawnrate.
		#Range: 0.0 ~ 100.0
		silverfishSpawnrateSH = 0.7
		#
		# Make Mob Spawners generate in rooms other than the Portal Room in Strongholds.
		# Note: Spawners in Portal Room will always remain.
		allowExtraSpawnersSH = true
		#
		# How rare are Strongholds.
		# 1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		strongholdSpawnrate = 80
		#
		# Use vanilla Stronghold instead of using this mod's modded version.
		# Note: The other Stronghold configs here will have no effect on vanilla Strongholds. 
		# WARNING: Nether Strongholds will be turned off too when this option is on.
		useVanillaStronghold = false
		#
		# Allow Nether-styled Strongholds to spawn in Nether category biomes.
		# Note: Eyes of Ender will work and show the closest Nether Stronghold too.
		allowNetherStronghold = true
		#
		# Allow Stonebrick styled Stronghold to generate in non-Nether biomes.
		allowStonebrickStronghold = true
		#
		# How large the Stronghold is on average as a percentage.
		# Note: The Stonghold is much larger by default. To get something 
		# closer to vanilla stronghold size, use the value of 60.
		# 10 for supertiny Strongholds and 2000 for supermassive Strongholds.
		#Range: 10.0 ~ 2000.0
		strongholdSizeSH = 75.0
		#
		# Controls whether loot chests spawn or not in the Stronghold.
		lootChestsSH = true

	["Structure Options"."Badlands Temple"]
		#
		# How rare are Nether Temples in Nether.
		# 1 for spawning in most chunks and 1001 for no spawn.
		#Range: 1 ~ 1001
		badlandsTempleSpawnrate = 30
		#
		# Controls whether loot chests spawn or not in Badlands Temples.
		lootChestsBT = true
		#
		# Add Jungle Fortress to modded jungle biomes.
		addBadlandsTempleToModdedBiomes = true

